edition = "2018"

#condense_wildcard_suffixes = true

#control_brace_style = "ClosingNextLine"

hard_tabs = true

#struct_field_align_threshold = 50

use_field_init_shorthand = true

use_try_shorthand = true

max_width = 180