[target.'cfg(all(target_arch = "x86_64", target_os = "windows"))']
    rustflags = ["-C", "target-cpu=native"]

[profile.release]
    lto = true
    codegen-units = 1
    opt-level = 3

[profile.dev.package."*"]
    codegen-units = 1
    opt-level = 3